#!/bin/sh

#sync time
timedatectl set-ntp true

#install base packages
pacstrap /mnt base linux linux-firmware base-devel vim networkmanager grub

read -p "Continue beyond base package install? "
echo "fstab generation..."
genfstab -U /mnt>>/mnt/etc/fstab

echo "copying files we need in the new filesystem.."
cp changeroot /mnt/root
mkdir /mnt/usr/share/wallpaper
cp Scenery_in_Plateau_by_Arto_Marttinen.jpg /mnt/usr/share/wallpaper

#-------------------------------
read -p "Let's change root?"
arch-chroot /mnt ~/changeroot
#-------------------------------

#copy important config and dotfiles 
#########FIX
cp .bashrc .xinitrc /mnt/home/tom #will be an error if user is not named tom
#########^FIX
cat hosts >> /mnt/etc/hosts 
cp profile /mnt/etc/profile
cp post /mnt/root
echo "That's all folks"

###NEXT
#/usr/local/bin programs for xsetroot
#brave browser
#yay
#no battery, no indicator
#/etc/xdg/termite config for transparency
