#!/bin/sh

#sync time
timedatectl set-ntp true

#install base packages
pacstrap /mnt base linux linux-firmware base-devel vim networkmanager grub

read -p "Continue beyond base package install... "
genfstab -U /mnt>>/mnt/etc/fstab
cp -v changeroot /mnt/root
mkdir /mnt/usr/share/wallpaper
cp -v Scenery_in_Plateau_by_Arto_Marttinen.jpg /mnt/usr/share/wallpaper

#-------------------------------
read -p "Let's change root?"
arch-chroot /mnt ~/changeroot
#-------------------------------

cp -v post homeconf/* homeconf/.* /mnt/home/tom
cp -v hosts /mnt/etc/hosts
cp -v profile /mnt/etc/profile
echo "complete"
