#!/bin/sh
#Run as your user, not root
#------------------------
#Rest of the packages. two terminals to be safe
sudo pacman -S --noconfirm ranger picom alsa-utils make go dmenu xorg-xsetroot xorg-xinit xorg-server git nitrogen rxvt-unicode termite redshift arandr

#YAY do for each package instead of all at once. 
git clone https://aur.archlinux.org/yay.git /home/tom/yay
cd /home/tom/yay
makepkg -i 
#yay -S brave-bin pacman-mirrorup gqview ffmpeg-compat-57 epson-inkjet-printer-escpr dashbinsh abeep-git urxvt-resize-font-git

#DWM
git clone https://github.com/Rosetho/dwm.git /home/tom/dwm
sudo make clean install /home/tom/dwm
cd;startx

mkdir ~/.local/bin
git clone https://github.com/Rosetho/bin.git /home/tom/.local/bin
xrdb ~/.Xresources
